const dialog=document.querySelector('#project-dialog'),zoom=document.querySelector('#zoom-dialog');let active=0,lastTrigger;
const img=(file,alt,cls='')=>`<img class="${cls}" src="assets/${file}" alt="${alt}" loading="lazy">`;
projects.forEach((p,i)=>{
 const open=`data-project="${i}"`;
 if(p.category==='branding'){
 document.querySelector('#branding-grid').insertAdjacentHTML('beforeend',`<article class="brand-project"><div class="brand-art"><button ${open} class="brand-logo-panel" aria-label="Open ${p.name} gallery, ${p.images.length} images"><span class="cover-logo">${img(p.logo,p.name+' complete logo')}</span><span class="brand-preview" aria-hidden="true">${p.images.slice(0,3).map((file,j)=>img(file,'','preview-photo preview-photo-'+j)).join('')}<span class="preview-label">Explore ${p.images.length} images ↗</span></span></button><div class="brand-palette" aria-label="${p.name} brand colors">${p.colors.map(c=>`<span class="color-orb" style="--orb-color:${c}" role="img" aria-label="Brand color ${c}" title="${c}"></span>`).join('')}<span class="palette-label">Brand palette</span></div><p class="touch-gallery-hint">Tap the logo to explore</p></div><button ${open} class="project-caption"><span><strong>${p.name}</strong><small>Logo & brand applications</small></span><span aria-hidden="true">↗</span></button></article>`);
 }else if(p.category==='social'){
 document.querySelector('#social-grid').insertAdjacentHTML('beforeend',`<article class="social-collection"><div class="collection-heading"><div><h3>${p.name}</h3><p>${p.images.length} designs / Social media</p></div><button ${open}>View collection ↗</button></div><div class="social-images">${p.images.map((file,j)=>`<button ${open} data-image-index="${j}" aria-label="View ${p.name}, design ${j+1}">${img(file,p.name+', design '+(j+1))}</button>`).join('')}</div></article>`);
 }else{
 document.querySelector('#visual-grid').insertAdjacentHTML('beforeend',`<article class="visual-project"><button ${open} aria-label="View Saudi National Day visual">${img(p.images[0],p.name+' campaign visual')}</button><button ${open} class="project-caption"><span><strong>${p.name}</strong><small>Standalone campaign visual</small></span><span aria-hidden="true">↗</span></button></article>`);
 }
});
function renderProject(i){active=(i+projects.length)%projects.length;const p=projects[active];document.querySelector('#project-title').textContent=p.name;document.querySelector('#project-category').textContent=p.label;document.querySelector('#project-index').textContent=p.category.toUpperCase()+' / SELECTED WORK';document.querySelector('#project-description').textContent=p.description;const website=document.querySelector('#project-website');website.hidden=!p.website;if(p.website){website.href=p.website;website.textContent='Visit brand website ↗'}else{website.removeAttribute('href');website.textContent=''};const gallery=document.querySelector('#project-images');gallery.className=p.category+'-gallery';const tile=(file,j)=>`<button data-zoom="assets/${file}" id="gallery-image-${j}" style="--image-ratio:${p.imageRatios[file]}" aria-label="Enlarge ${p.name}, image ${j+1}">${img(file,p.name+', design '+(j+1))}</button>`;if(p.category==='branding'){let rows=`<div class="gallery-row gallery-hero">${tile(p.images[0],0)}</div>`;for(let j=1;j<p.images.length;j+=2){rows+=`<div class="gallery-row">${tile(p.images[j],j)}${p.images[j+1]?tile(p.images[j+1],j+1):''}</div>`}gallery.innerHTML=`<div class="gallery-logo">${img(p.logo,p.name+' logo')}</div>`+rows}else{gallery.innerHTML=p.images.map(tile).join('')};dialog.scrollTop=0;history.replaceState(null,'',`#project-${p.id}`)}
function openProject(i,trigger){document.querySelectorAll('.brand-logo-panel').forEach(b=>b.dispatchEvent(new Event('previewstop')));lastTrigger=trigger;renderProject(i);if(!dialog.open)dialog.showModal();document.body.classList.add('modal-open');document.querySelector('#close-project').focus();if(trigger?.dataset.imageIndex){document.querySelector('#gallery-image-'+trigger.dataset.imageIndex)?.scrollIntoView({block:'center'})}}
document.querySelector('#work').addEventListener('click',e=>{const b=e.target.closest('[data-project]');if(b)openProject(+b.dataset.project,b)});
document.querySelector('#close-project').addEventListener('click',()=>dialog.close());dialog.addEventListener('close',()=>{document.body.classList.remove('modal-open');history.replaceState(null,'','#work');lastTrigger?.focus()});document.querySelector('#previous-project').addEventListener('click',()=>renderProject(active-1));document.querySelector('#next-project').addEventListener('click',()=>renderProject(active+1));dialog.addEventListener('keydown',e=>{if(zoom.open)return;if(e.key==='ArrowRight'){e.preventDefault();renderProject(active+1)}if(e.key==='ArrowLeft'){e.preventDefault();renderProject(active-1)}});
document.querySelector('#project-images').addEventListener('click',e=>{const b=e.target.closest('[data-zoom]');if(!b)return;const im=document.querySelector('#zoom-image');im.src=b.dataset.zoom;im.alt=b.querySelector('img').alt;zoom.showModal()});document.querySelector('#close-zoom').addEventListener('click',()=>zoom.close());[dialog,zoom].forEach(d=>d.addEventListener('click',e=>{if(e.target===d){const r=d.getBoundingClientRect();if(e.clientX<r.left||e.clientX>r.right||e.clientY<r.top||e.clientY>r.bottom)d.close()}}));
const menu=document.querySelector('.menu-button'),header=document.querySelector('header'),mainNav=document.querySelector('#primary-navigation');
function closeMenu(){header.classList.remove('menu-open');menu.setAttribute('aria-expanded','false')}
menu.addEventListener('click',()=>{const opened=header.classList.toggle('menu-open');menu.setAttribute('aria-expanded',String(opened))});
mainNav.addEventListener('click',e=>{if(e.target.closest('a'))closeMenu()});
document.addEventListener('keydown',e=>{if(e.key==='Escape'&&header.classList.contains('menu-open')){closeMenu();menu.focus()}});
window.matchMedia('(min-width:901px)').addEventListener('change',closeMenu);
document.querySelector('#year').textContent=new Date().getFullYear();const initial=projects.findIndex(p=>location.hash===`#project-${p.id}`);if(initial>=0)openProject(initial,document.querySelector(`[data-project="${initial}"]`));

// Hover and keyboard previews; touch users open the same gallery with one tap.
const reducedMotion=window.matchMedia('(prefers-reduced-motion: reduce)');
const finePointer=window.matchMedia('(hover: hover) and (pointer: fine)');
document.querySelectorAll('.brand-logo-panel').forEach(button=>{
 const p=projects[Number(button.dataset.project)];const photos=button.querySelectorAll('.preview-photo');let timer=null,delay=null,frame=0;
 function stop(){clearTimeout(delay);clearInterval(timer);timer=null;delay=null;button.classList.remove('is-previewing','preview-wait');frame=0;photos.forEach((im,j)=>{im.src='assets/'+p.images[j%p.images.length]})}
 function start(){if(timer||delay||dialog.open)return;button.classList.add('preview-wait');delay=setTimeout(()=>{delay=null;if(dialog.open)return;button.classList.remove('preview-wait');button.classList.add('is-previewing');if(!reducedMotion.matches)timer=setInterval(()=>{frame=(frame+1)%p.images.length;photos.forEach((im,j)=>{im.src='assets/'+p.images[(frame+j)%p.images.length]});},2400)},1000)}
 button.addEventListener('pointerenter',()=>{if(finePointer.matches)start()});button.addEventListener('pointerleave',stop);button.addEventListener('focus',()=>{if(finePointer.matches)start()});button.addEventListener('blur',stop);button.addEventListener('previewstop',stop);reducedMotion.addEventListener('change',stop);document.addEventListener('visibilitychange',()=>{if(document.hidden)stop()});
});
if('IntersectionObserver' in window){const revealObserver=new IntersectionObserver(entries=>{entries.forEach(entry=>{if(entry.isIntersecting){if(!reducedMotion.matches)entry.target.classList.add('reveal-enter');revealObserver.unobserve(entry.target)}})},{threshold:.1});document.querySelectorAll('.brand-project,.social-collection,.category-heading,.service-grid article,.about-grid,.software-card,.timeline article,.contact-layout').forEach(el=>revealObserver.observe(el))}

let scrollScheduled=false;
function updateScroll(){const extent=document.documentElement.scrollHeight-window.innerHeight;document.querySelector('.scroll-progress').style.transform='scaleX('+(extent>0?window.scrollY/extent:0)+')';header.classList.toggle('has-scrolled',window.scrollY>20);scrollScheduled=false}
window.addEventListener('scroll',()=>{if(!scrollScheduled){scrollScheduled=true;requestAnimationFrame(updateScroll)}},{passive:true});updateScroll();
if('IntersectionObserver' in window){const navObserver=new IntersectionObserver(entries=>{entries.forEach(e=>{if(e.isIntersecting){mainNav.querySelectorAll('a').forEach(a=>{if(a.hash==='#'+e.target.id)a.setAttribute('aria-current','location');else a.removeAttribute('aria-current')})}})},{rootMargin:'-15% 0px -60% 0px'});['about','skills','experience','work','contact'].forEach(id=>navObserver.observe(document.getElementById(id)))}

document.addEventListener("click",e=>{if(header.classList.contains("menu-open")&&!header.contains(e.target))closeMenu()});
